import type { Metadata } from "next";
import { Amaranth, Concert_One, Libre_Barcode_128, Roboto } from "next/font/google";
import "./globals.css";

export const metadata: Metadata = {
  title: "Jamin Chan",
  description: "Generated by create next app",
};

const globalFont = Amaranth({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="{globalFont.className}">
      <body className={globalFont.className}>{children}</body>
    </html>
  );
}
